name: Basic CI
on:
  push:
    branches: [ main]
jobs:
  build:
    runs-on: ubuntu-Latest
    steps:
      - uses: actions/checkout@4
      - name: Run build
        run: echo "CI is running"
       




  
